### ISSUE TITLE
Package suggestion: scikit-learn armv7

### ISSUE THREAD

**Issue by Lash-L** [alpine-wheels/index#1028]
**Link to the package on PyPI:** https://pypi.org/project/scikit-learn/

- [ ] Please add a version of the package that is not the latest.
- [ ] Please add a package for a version of Python that is not the latest.
- [x] Please add a package for a platform other than linux/amd64

Having a wheel for scikit-learn that could be run on alpine + my rpi(armv7) would be appreciated

**Comment by williamjacksn** [comment]
I just added scikit-learn 1.5.0 for musl on arm/v7, please let me know if it works for you.
