### ISSUE TITLE
support `/simple/` index 

### ISSUE THREAD

**Issue by atharvai** [alpine-wheels/index#814]
Currently this package repository only supports `/index` endpoint. Many tools and proxy solutions such as Sonatype Nexus require index to be available at `/simple` endpoint. This is also part of PEP 503 compliance.

**Comment by williamjacksn** [comment]
Having `/simple/` somewhere in the URL is not required by the spec. Do you have a link to documentation for Sonatype Nexus or exact error details that explain the problem?

**Comment by atharvai** [comment]
Nexus reference: https://issues.sonatype.org/browse/NEXUS-29223
Interpreted the pep as "simple" api is part of it. https://peps.python.org/pep-0503/ I recognise that the folder structure is important.

**Comment by williamjacksn** [comment]
Index content is now also available at https://alpine-wheels.github.io/index/-/simple/

**Comment by atharvai** [comment]
wow awesome thank you for quick response. All good!
