### ISSUE TITLE
arm/v7 & arm64 packages

### ISSUE THREAD

**Issue by modem7** [alpine-wheels/index#828]
Are there any plans to host arm/v7 & arm64 packages also?

Even just the arm64 would suffice for numerous users.

As an example: numpy.

Thank you!

**Comment by modem7** [comment]
Although this might be resolved by using pep656? Unsure as I'm a noob at Python. 

Just saw this as well: https://github.com/numpy/numpy/issues/20089

**Comment by williamjacksn** [comment]
I don’t have experience with this so it would take some research to see how to do it using GitHub actions.

Do you want to try to implement this over at https://github.com/alpine-wheels/numpy ?

**Comment by modem7** [comment]
> I don’t have experience with this so it would take some research to see how to do it using GitHub actions.
> 
> Do you want to try to implement this over at https://github.com/alpine-wheels/numpy ?

Sounds like a plan.

However, I'd recommend we wait until https://github.com/numpy/numpy/issues/20089 is done lest we duplicate efforts.

I think if we can figure out this one once they do the final work, we can probably *relatively* easily do the same for the rest of the packages too.

Would you mind keeping this on hold until then?

**Comment by williamjacksn** [comment]
> Would you mind keeping this on hold until then?

Always happy to do less work. If numpy does land musllinux wheels, I can probably stop building that package completely.

Out of curiosity, was numpy the only package you need a wheel for on ARM?

**Comment by modem7** [comment]
> > Would you mind keeping this on hold until then?
> 
> Always happy to do less work. If numpy does land musllinux wheels, I can probably stop building that package completely.
> 
> Out of curiosity, was numpy the only package you need a wheel for on ARM?

Totally agree! Would definitely make life easier for everyone!

The other one that's common for me is the borgbackup wheel and its dependencies.

**Comment by modem7** [comment]
@williamjacksn last night, I was having a play with cibuildwheel with sdist. 

https://github.com/modem7/wheels

Might be useful? I'm still tinkering currently, but it's certainly looking good for both multiarch + Alpine

**Comment by williamjacksn** [comment]
@modem7 I had a personal need for linux/arm64 packages so I set up a system to build them. Do you still need alternate platforms for some packages?

**Comment by modem7** [comment]
> @modem7 I had a personal need for linux/arm64 packages so I set up a system to build them. Do you still need alternate platforms for some packages?

Hey bud, all good this end for now! Thanks!

**Comment by williamjacksn** [comment]
If anyone finds this issue in the future, please open a new issue a specify which package and which platform you want a wheel for.
