### ISSUE TITLE
Package suggestion: cryptg

### ISSUE THREAD

**Issue by pseudokawaii** [alpine-wheels/index#829]
**Link to the package on PyPI:** https://pypi.org/project/cryptg

- [ ] Please add a version of the package that is not the latest.
- [ ] Please add a package for a version of Python that is not the latest.

**Comment by williamjacksn** [comment]
Fixed in #831

**Comment by williamjacksn** [comment]
What version of Python are you using this package with?

**Comment by williamjacksn** [comment]
Package for 3.10 added in #832
