### ISSUE TITLE
Package suggestion:  reportlab

### ISSUE THREAD

**Issue by RonNabuurs** [alpine-wheels/index#998]
**Link to the package on PyPI:** https://pypi.org/project/reportlab

In our project we are using Python 3.11 and reportlab 3.6.12, it would be wonderfull if this packages could be added to the repo.

- [ ] Please add a version of the package that is not the latest.
- [ ] Please add a package for a version of Python that is not the latest.
- [ ] Please add a package for a platform other than linux/amd64

**Comment by williamjacksn** [comment]
I added the package you requested.
